#!/usr/bin/env ruby
# Author Jim Conner

$: << File.join(__dir__,'lib')

require 'btree'

node       = Node.new('aRoot', 5)
controller = Controller.new(node)
controller.insert('aNode',1)
controller.insert('bNode',5)
controller.insert('aNode',6)

controller.printOrderedNames
